### ISSUE TITLE
Parsing serialized RDFlib Graphs breaks (possible bug?)

### ISSUE THREAD

**Issue by Ga11u** [RDFLib/rdflib#1395]
Some URI cannot be parsed with RDFlib, even when those ones have been produced by RDFlib itself and they are correct.

For example:

If we have the following RDF/TURTLE:

```
@prefix ex: <https://example.org/term#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix dbr: <http://dbpedia.org/resource/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<http://example.org/entity> ex:anchorOf "This press"^^xsd:string ;
            a <http://dbpedia.org/resource/This_(journal)> .
```

We load the TTL using `g.parse(data=ttl, format="turtle")` and we serialize it with `g.serialize(format='turtle')` we got:

```
@prefix dbr: <http://dbpedia.org/resource/> .
@prefix ex: <https://example.org/term#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.org/entity> a dbr:This_(journal) ;
    ex:anchorOf "This press"^^xsd:string .
```

Then, if we load the output again with `g.parse(data=ttl, format="turtle")`, we get the following **errorr**:

> rdflib.plugins.parsers.notation3.BadSyntax: at line 5 of <>:
Bad syntax (expected '.' or '}' or ']' at end of statement) at ^ in:
"...b'/2001/XMLSchema#> .\n\n<http://example.org/entity> a dbr:This_'^b'(journal) ;\n    ex:anchorOf "This press"^^xsd:string .'"

The error is cause by `dbr:This_(journal)`, more presicely by the '(' and ')'. It seems RDFlib does not like its own output.

Any ideas on what may be happing here?

**Comment by nicholascar** [comment]
@Ga11u yes it is a bug and I think we've seen this pop up here and there but thanks to you for making the problem explicit now in an Issue. I've flagged it as a bug.

Surely if a URI shortening with prefix makes an invalid cURI, then the shortening should not be implemented for that URI, even if the prefix is set!

I've tried this data in [Jena](https://jena.apache.org/) like so:

```java
// test data, with an additional test triple
String d1 = "@prefix ex: <https://example.org/term#> ."+
            "@prefix xsd: <http://www.w3.org/2001/XMLSchema#>."+
            "@prefix dbr: <http://dbpedia.org/resource/> ."+
            "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> ."+
            ""+
            "<http://example.org/entity> ex:anchorOf \"This press\"^^xsd:string ;"+
            "           a <http://dbpedia.org/resource/This_(journal)> ;"+
            "           ex:something <http://dbpedia.org/resource/OtherFakeResource> .";

// read the Turtle data into a Jena Model
Model m1 = ModelFactory.createDefaultModel();
m1.read(IOUtils.toInputStream(d1, "UTF-8"), null, "TTL");

// print the Jena Model in Turtle to check
StringWriter d2 = new StringWriter();
m1.write(System.out, "TTL" );

// we get:
/*
    @prefix dbr: <http://dbpedia.org/resource/> .
    @prefix ex:  <https://example.org/term#> .
    @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

    <http://example.org/entity>
            rdf:type      <http://dbpedia.org/resource/This_(journal)> ;
            ex:anchorOf   "This press" ;
            ex:something  dbr:OtherFakeResource .
*/
```

So Jena compresses the `http://dbpedia.org/resource/OtherFakeResource` since it makes a valid cURI, but it doesn't compress `http://dbpedia.org/resource/This_(journal)` and thus can repeat parse/write cycles just fine.

**Comment by nicholascar** [comment]
Renaming issue to better capture the problem

**Comment by nicholascar** [comment]
Need to check if `dbr:This_(journal)` really is an invalid cURI or rather an invalid Turtle prefixed URI (I forget the exact name).

**Comment by kone807** [comment]
@nicholascar  I want to work on this issue. Can you suggest how can I start with it? I have cloned the repo and reproduced the error. What possible fixes can we do here?

**Comment by Ga11u** [comment]
> @nicholascar I want to work on this issue. Can you suggest how can I start with it? I have cloned the repo and reproduced the error. Can you please suggest some possible fixes? Thank you!

One possible workaround is to check whether the reference part of the [CURIE](https://www.w3.org/TR/curie/) (i.e., the  part after the ```:```) contains ```(``` , ```)```, ```[```, ```]``` or any other character that may cause the error. If it contains the character then the RDFlib parses afull URI instead of a CURIE. 

This solution should emulate the same behaviour as Jena. Hower, I am not sure if this is the optimal or best way to go as we are not solving the problem, just adding a patch.

(I am using the word CURIE instead of cURI. They are the same, but I think the W3C uses CURIE)

**Comment by nicholascar** [comment]
@kone807 I do think the starting point here is to review the formal definitions of CURIE and the Turtle specification, as @Ga11u says above and then, when they are known to you, create tests that should pass but currently fail. If you can do that, you might then be able to either design a solution or ask other RDFLib maintainers for assistance. 

We really do need to confirm what is allowed and then we can see if the Jena approach is valid. If it is, I think the coding to find certain characters in the potential CURIES won't be that hard so preventing RDFLib from shortening problematic CURIES will be possible.

**Comment by kone807** [comment]
[CURIE](https://www.w3.org/TR/curie/#s_syntax) mentions the following -

> The concatenation of the prefix value associated with a CURIE and its reference MUST be an [IRI](https://www.w3.org/TR/curie/#ref_IRI) (as defined by the IRI production in [IRI]).

According to URI rules, '(', ')' are valid values. Using '[', ']', '{', '}', '^' give an error.

Also, I tried to reproduce the error on my system and I don't seem to get one. Here's the code - 

`from rdflib import Graph
import pprint

"""
test.ttl

@prefix ex: <https://example.org/term#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix dbr: <http://dbpedia.org/resource/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<http://example.org/entity> ex:anchorOf "This press"^^xsd:string ;
            a <http://dbpedia.org/resource/This_(journal)> .
"""

g = Graph()
g.parse("test.ttl",format="ttl")

for stmt in g:
	pprint.pprint(stmt)

print("\n",25*"==","\n")

g.serialize(destination="test_parsed.ttl")

"""
test_parsed.ttl

@prefix dbr: <http://dbpedia.org/resource/> .
@prefix ex: <https://example.org/term#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.org/entity> a dbr:This_\(journal\) ;
    ex:anchorOf "This press"^^xsd:string .
"""

g1 = Graph()
g1.parse("test_parsed.ttl",format="ttl")

for stmt in g1:
	pprint.pprint(stmt)
`

**Observation:** In contrast to original snippet, the parenthesis are now preceded by a forward slash which somehow results in correct parsing.

**Comment by Ga11u** [comment]
@kone807 Have you tried to serialize without saving into a file, just `g.serialize()` ? You should get a string which I assume it will not contain the back slash and then, you can parse the string again. This should give you the error.

**Comment by nicholascar** [comment]
There are a couple of different scenarios in which Python -> RDF -> Python -> RDF cycles break due to string encoding, for example, regular expressions in SHACL `sh:pattern` properties. The problem there is that there are just too many different encoding systems at play that require different kinds of character escaping which get in each others way! It may not always be feasible to solve absolutely all of these issues.

If the cycle above passes, let's write that up as a pytest test. Then yes, another one can be made that serializes/deserializes to a file and we can see if that one fails.

**Comment by kone807** [comment]
@Ga11u  I tried and still works like a charm - 

```python
from rdflib import Graph
import pprint

"""
test.ttl

@prefix ex: <https://example.org/term#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix dbr: <http://dbpedia.org/resource/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<http://example.org/entity> ex:anchorOf "This press"^^xsd:string ;
            a <http://dbpedia.org/resource/This_(journal)> .
"""

g = Graph()
g.parse("test.ttl",format="ttl")

for stmt in g:
	pprint.pprint(stmt)

print("\n",25*"==","\n")

s = g.serialize()

print(s)
"""
test_parsed.ttl

@prefix dbr: <http://dbpedia.org/resource/> .
@prefix ex: <https://example.org/term#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.org/entity> a dbr:This_\(journal\) ;
    ex:anchorOf "This press"^^xsd:string .
"""

g1 = Graph()
g1.parse(data=s,format="ttl")

for stmt in g1:
	pprint.pprint(stmt)
```

**Comment by kone807** [comment]
@nicholascar  so I should try to find a cycle which leads to the intended error and write similar test cases for it (as currently I can't seem to replicate it using RDF -> Python -> RDF -> Python or RDf -> Python -> String -> Python). Did I understand it correctly?

**Comment by niklasl** [comment]
It is important here (in parsing and serializing various forms) to carefully notice and comply with the appropriate specifications:

* [QNames](https://www.w3.org/TR/REC-xml-names/#NT-QName) (for XML elements and attributes)
* [PNames](https://www.w3.org/TR/turtle/#grammar-production-PNAME_NS) (for Turtle, TriG and SPARQL)
* [CURIEs](https://www.w3.org/TR/rdfa-core/#s_curies) (for RDFa, mainly)
* [Compact IRIs](https://www.w3.org/TR/json-ld/#dfn-compact-iri) (for JSON-LD; mostly(?) identical to CURIEs)

This list is informally ordered from most to least restrictive in terms of what characters are allowed. In PNames, more are allowed than in QNames, but some have to be escaped; in CURIEs, no valid IRI character has to be escaped in the local part. The rules for how prefixes are defined and their forms also differ. (In all but QNames, the `_` prefix is used for blank node identifiers. In RDFa and JSON-LD, CURIEs mainly share the same  lexical space as regular IRIs, for better or worse.)

**Comment by Ga11u** [comment]
@kone807 Have you tried with ```format="turtle"``` instead of ```ttl``` ?

**Comment by gjhiggins** [comment]
> Some cURIs cannot be parsed with RDFlib, even those produced by RDFlib.

That may be true but I can't seem to reproduce your particular issue of failure to parse the serialized example:
```py
def test_turtle_serialize():
    test_ttl = """@prefix ex: <https://example.org/term#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix dbr: <http://dbpedia.org/resource/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<http://example.org/entity> ex:anchorOf "This press"^^xsd:string ;
            a <http://dbpedia.org/resource/This_(journal)> ."""

    g = Graph()

    g.parse(data=test_ttl, format="turtle")

    assert sorted(list(g))[0] == (
        URIRef('http://example.org/entity'),
        URIRef('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'),
        URIRef('http://dbpedia.org/resource/This_(journal)')
    )

    data_str = g.serialize(format="turtle")

    assert g.serialize(format='turtle') == """@prefix dbr: <http://dbpedia.org/resource/> .
@prefix ex: <https://example.org/term#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.org/entity> a dbr:This_\(journal\) ;
    ex:anchorOf "This press"^^xsd:string .

"""
    g1 = Graph()
    g1.parse(data=data_str, format="turtle")

    assert sorted(list(g1))[0] == (
        URIRef('http://example.org/entity'),
        URIRef('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'),
        URIRef('http://dbpedia.org/resource/This_(journal)')
    )

    assert g1.serialize(format='turtle') == """@prefix dbr: <http://dbpedia.org/resource/> .
@prefix ex: <https://example.org/term#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.org/entity> a dbr:This_\(journal\) ;
    ex:anchorOf "This press"^^xsd:string .

"""

    g1.serialize("/tmp/test.ttl", format='turtle')

    """
cat /tmp/test.ttl 

@prefix dbr: <http://dbpedia.org/resource/> .
@prefix ex: <https://example.org/term#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.org/entity> a dbr:This_\(journal\) ;
    ex:anchorOf "This press"^^xsd:string .

    """

    g2 = Graph()
    g2.parse("/tmp/test.ttl", format="turtle")

    assert sorted(list(g2))[0] == (
        URIRef('http://example.org/entity'),
        URIRef('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'),
        URIRef('http://dbpedia.org/resource/This_(journal)')
    )

    assert g2.serialize(format='turtle') == """@prefix dbr: <http://dbpedia.org/resource/> .
@prefix ex: <https://example.org/term#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.org/entity> a dbr:This_\(journal\) ;
    ex:anchorOf "This press"^^xsd:string .

"""
```

**Comment by gjhiggins** [comment]
> Some cURIs cannot be parsed with RDFlib, even those produced by RDFlib.

That may be true but I can't seem to reproduce the issue you encountered with parsing the serialized example whether it's serialized to a string and parsed, serialized and directly fed to the parser or serialized to and read back from a file.

```py
def test_turtle_serialize():
    test_ttl = """@prefix ex: <https://example.org/term#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix dbr: <http://dbpedia.org/resource/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<http://example.org/entity> ex:anchorOf "This press"^^xsd:string ;
            a <http://dbpedia.org/resource/This_(journal)> .
"""

    expected_statement = (
        URIRef('http://example.org/entity'),
        URIRef('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'),
        URIRef('http://dbpedia.org/resource/This_(journal)')
    )

    g = Graph()

    g.parse(data=test_ttl, format="turtle")
    assert sorted(list(g))[0] == expected_error

    data_str = g.serialize(format="turtle")

    assert data_str == """\
@prefix dbr: <http://dbpedia.org/resource/> .
@prefix ex: <https://example.org/term#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.org/entity> a dbr:This_\(journal\) ;
    ex:anchorOf "This press"^^xsd:string .

"""
    g1 = Graph()
    g1.parse(data=data_str, format="turtle")
    assert sorted(list(g1))[0] == expected_statement

    assert g1.serialize(format='turtle') == data_str

    g2 = Graph()

    g2.parse(data=g1.serialize(format='turtle'), format="turtle")

    assert sorted(list(g2))[0] == expected_statement

    assert g2.serialize(format='turtle') == data_str

    g.serialize("/tmp/test.ttl", format='turtle')

    """
$ cat /tmp/test.ttl 
@prefix dbr: <http://dbpedia.org/resource/> .
@prefix ex: <https://example.org/term#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.org/entity> a dbr:This_\(journal\) ;
    ex:anchorOf "This press"^^xsd:string .
    """
    data = open("/tmp/test.ttl", 'r').read()

    g3 = Graph()
    g3.parse(data=data, format="turtle")

    assert sorted(list(g3))[0] == expected_statement

    assert g3.serialize(format='turtle') == data_str

    with open("/tmp/test.ttl", "w") as fp:
        fp.write(test_ttl)
        fp.close()

    """
$ cat /tmp/test.ttl 
@prefix ex: <https://example.org/term#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix dbr: <http://dbpedia.org/resource/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<http://example.org/entity> ex:anchorOf "This press"^^xsd:string ;
            a <http://dbpedia.org/resource/This_(journal)> .
    """

    g4 = Graph()
    datafile = open("/tmp/test.ttl", 'r')
    g4.parse(file=datafile, format="turtle")

    assert sorted(list(g4))[0] == expected_statement

    assert g4.serialize(format='turtle') == data_str

    g5 = Graph()
    g5.parse("/tmp/test.ttl", format="turtle")

    assert sorted(list(g5))[0] == expected_statement

    assert g5.serialize(format='turtle') == data_str
```

**Comment by Ga11u** [comment]
The bug was identified last year using the RDFlib v5 and we are currently at RDFlib v6.1. I revised the releases and it seams there have been several updates on the parsers and serializers . Is it posible that the bug is already fixed? At least, the outputs you show presents a back slash wich was not provided in the previous versions.

However, I am wondering if adding a backslash is the best approach and how compatible is it with other libraries or applications. One possible drawback of this approach would be string parsing using regex or other libraries that may resolve ```dbr:This_\(journal\)``` to ```<http://dbpedia.org/resource/This_\(journal\)>``` instead of its original form. Using regex it would not be obvious that ```This_(journal)``` is the same as ```This_\(journal\)``` . And also,  using entity matching ```dbr:This_\(journal\)```  may not be identified as the same as  ```dbr:This_(journal)``` .

**Comment by gjhiggins** [comment]
> The bug was identified last year using the RDFlib v5 and we are currently at RDFlib v6.1. I revised the releases and it seams there have been several updates on the parsers and serializers . Is it posible that the bug is already fixed? At least, the outputs you show present a backslash wich was not provided in the previous versions.

Yes, that's entirely possible. I'm just trying to narrow down the scope of the extant issue is all.

> However, I am wondering if adding a backslash is the best approach and how compatible it is with other libraries or applications.

Fair comment, it's not compatible, at least as far as [RDFConvert](https://sourceforge.net/projects/rdfconvert/) (elderly but still serviceable, just like yours truly :smile:) is concerned:
```bash
$ ~/Apps/rdfconvert-0.4/bin/rdfconvert.sh -i Turtle -o N3 /tmp/test.ttl 
11:51:39.534 [main] ERROR nz.co.rivuli.rio.convert.RDFConvert - Syntax error in input file:
11:51:39.535 [main] ERROR nz.co.rivuli.rio.convert.RDFConvert - IRI includes string escapes: '\40' [line 7]
```
So that leaves us back at @niklasl's cautioning observation: "It is important here (in parsing and serializing various forms) to carefully notice and comply with the appropriate specifications"

**Comment by ioggstream** [comment]
It seems to work now with rdflib 7.0.0 (tested via ttlser)

```bash
$ echo '
@prefix foo: <http://foo#> .
<http://foo#bar(ciao)> foo:a "ciao" .
'  | ttlfmt
@prefix foo: <http://foo#> .

### Annotations

foo:bar\(ciao\) foo:a "ciao" .

### Serialized using the ttlser deterministic serializer v1.2.1
```

**Comment by lisat-dstg** [comment]
This is not fixed. Turtle RDF roundtrip serialisation fails with backslash escaping. I am using **rdflib 7.1.0**.

If I deserialise the following Turtle RDF and reserialise, the backslash on the "cc:60_\\\%_value" prefixed name is dropped and subsequent deserialisation fails with error.

```
@prefix cc: <http://aa.bb#> .
@prefix ies: <http://ies.data.gov.uk/ontology/ies4#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
cc:60_\%_value a ies:MeasureValue ;
  ies:representationValue "60"^^xsd:decimal ;
  rdfs:label "60 %" .
```

**Comment by lisat-dstg** [comment]
I would like to fix this, but I'm new to the rdflib community. Any advice before I crack on?

**Comment by WhiteGobo** [comment]
@lisat-dstg There is a [developers guide](https://rdflib.readthedocs.io/en/latest/developers/) and a [contribution guide](https://rdflib.readthedocs.io/en/latest/CONTRIBUTING/) but i guess, as you run the roundtrip test you already knew that.
The turtle parser is at `rdflib.plugins.parsers.notation3.TurtleParser` and the serializer at `rdflib.plugins.serializers.turtle.TurtleSerializer`. You can also access the triples directly without serializing with something like `list(g)`.
If you want the patch in version 7.x instead of version 8 you can use the 7.x branch from the main-repository as start point/base.
I hope this information is helpful

**Comment by lisat-dstg** [comment]
Draft PR at https://github.com/RDFLib/rdflib/pull/3364/ . Please advise. I'm new to contributing and can't figure out which main branch I'm meant to be targetting. For a bug fix, is it better to fix in a branch off main and then backport to 7.x or start directly with 7.x ? I verified the new tests break in both spots so it's definitely still a bug in both v7.5 and main branch.

**Comment by edmondchuc** [comment]
Hi @lisat-dstg, thanks for looking into this issue. When it comes to bug fixes that are applicable to both v7 and `main`, please branch off `7.x`. After each v7 release, we will merge the fixes into `main`.

**Comment by lisat-dstg** [comment]
Ready PR #3364

**Comment by lisat-dstg** [comment]
Ready again.

The test and fix is now very precisely targeted to escaped percent character in a localname. This works in Jena turtle serialiser/parser just fine. Rdflib must have missed it due to percent character appearing in the grammar specifically to percent-escape other/unprintable characters with 2-digit hexadecimal sequence.

The fix is using a precompiled regex to detect percent (%) characters not followed by 2-digit hex sequence. Such characters are replaced by blackslash plus percent character.

As requested also took opportunity to rename getQName function to get_pname where it appeared to be in fact getting a Prefixed Name. This was relevant to or touched four serialisers: Turtle, Long turtle, Trig and N3.

**Comment by lisat-dstg** [comment]
I think this one can be closed. Thanks @edmondchuc . I accidentally misspelt the regex variable name and duplicated it unnecessarily but didn't have a chance to get back to my rdflib dev envt to fix. That can be cleaned up later if desired.

**Comment by edmondchuc** [comment]
@lisat-dstg no problem, feel free to open a follow-up PR to clean up the variable name.

Closing issue as it's been addressed in https://github.com/RDFLib/rdflib/pull/3364.
